repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        stages: [commit]
        language: system
        entry: bash -c 'poetry run ruff format . --preview && git add .'
        pass_filenames: false
